### ISSUE TITLE
Not generate release apk

### ISSUE THREAD

**Issue by GauravCreed** [timusus/Shuttle#100]
Hi @kfarst 

I am user your code which is open source.
now i am doing little changes in code and some add functionality in this code.

now i am not  able to generate **sign apk** am i forgot something? then please guide me.  please

Thanks (_)

**Comment by timusus** [comment]
In order to compile release builds for Shuttle, you need to provide your own keystore, store password and Google Services JSON file.

If you just want to quickly get a build up and running on your phone, you need to switch to the debug variant instead.

The release variant is what I use to build Play Store production builds, hence why I have removed the keystore, API keys, etc.

**Comment by GauravCreed** [comment]
Hey @kfarst 

I just change this part as per my requirement.
`signingConfigs {
        release {
            Properties properties = getProperties('../keystore.properties')
            storeFile file(getProperty(properties, 'store'))
            keyAlias getProperty(properties, 'alias')
            storePassword getProperty(properties, 'storePass')
            keyPassword getProperty(properties, 'pass')
        }
    }`


i can't change json part because i don't need it, still it will not happen.

Thanks for the response.
(_)
