### ISSUE TITLE
Toast notification has dark text

### ISSUE THREAD

**Issue by cocobelgica** [timusus/Shuttle#193]
**Shuttle version:**
 
 v2.0.0-beta12 (Free)
 
**Device, OS:**
 
Android Nougat 7.1.2

**Description of bug:**
 
Toast notification uses dark text color which makes ot unreadable.
 
**Steps to reproduce:**
 
 1. Try adding a song to the play queue
 2. Toast notification pops out
 
**Expected outcome:**
 
Text color should be lighter as the toast notification BG color is already dark
 
**Observations/Actual Result:**
 
 Text color is dark on dark background.

**Comment by timusus** [comment]
Thanks for the report.

Which device are you using?

Also, which Shuttle theme?

**Comment by cocobelgica** [comment]
I'm using a custom ROM, AOSP Extended, running Android 7.1.2. Device is Lenovo K3 Note. This happens regardless of the theme, light or dark. Even using the default color scheme.

**Comment by timusus** [comment]
This is a problem with the ROM, rather than Shuttle. It looks like they're doing some customisation to the Toast layout, which makes it impossible for Shuttle to detect and not theme. 

Looking at their commit history, it's possible they've actually made some recent changes which might resolve this issue.
