### ISSUE TITLE
Remove from queue - removes all instances of song

### ISSUE THREAD

**Issue by timusus** [timusus/Shuttle#198]
**Shuttle version:**
 
 v2.0.0-beta
 
**Device, OS:**
 
Any

**Description of bug:**
 
When removing a song from the queue, all instances of that song are removed.

**Steps to reproduce:**

These steps may change if #197 is resolved.

1. Go to now playing queue
2. Click on 'overflow menu' for a song other than the current song
3. Choose 'play next'
4. Observe the song is in its original position, as well as in the 'next' position.
5. Click on the 'overflow menu', choose 'remove'
6. Observe both instances of the song are removed from the queue

**Comment by lastbulletbender** [comment]
So I looked into it and found out that the root cause of this is because the function removeTracks() in MusicService.java uses playList.removeAll() and shuffleList.removeAll().

Since removeTracks() does not itself take the position, is there any way to get which occurrence has to be removed if there are multiple occurrences in the queue?

**Comment by timusus** [comment]
I think a `position` argument can be passed in to `removeTracks`. For the `currentList` (which is either `playList` or `shuffleList` depending on the current mode), we can remove the item at that position. For the not-current list, we can just remove the first occurrence of that item.

Feel free to hit me up on Slack:
http://shuttle-slack-inviter.herokuapp.com/

**Comment by timusus** [comment]
Resolved with #219
