### ISSUE TITLE
feature request: Endless/infinite mode

### ISSUE THREAD

**Issue by ghost** [timusus/Shuttle#20]
I hope that feature requests are allowed :smile:

One thing I discovered with a media player was called the "endless" mode. Means that when I listen to a playlist and the playlist *finished* the app searches for tracks in my db with same or close-to Genres/BPM etc. Like if I have a playlist with like 20 tracks with the Genre DnB it searches automatically for tracks with the Genre DnB in my db so the music never stops. Would be cool to have that.

**Comment by icarapovic** [comment]
Endless/Infinite mode would be "Repeat all" :D 

Basically it used the most frequent genre from the playlist and started playing them all after the playlist ended. Should not be hard to implement, but since it is like a "smart" feature, more thoughts should be put into how this should actually work.

**Comment by timusus** [comment]
Closed in favour of #11
