### ISSUE TITLE
Shuttle starts when hand is brushed across locked screen accidentally.

### ISSUE THREAD

**Issue by raindropsfromsky** [timusus/Shuttle#215]
**Shuttle version:**
v2.0.0. beta 12
 
**Device, OS:**
OnePlus 3T
OxygenOS 4.5.1 (Android 7.1.1)

**Description of bug:**
Since last one month, I am facing a weird problem: When the phone is locked, and if my fingers brush against the screen, Shuttle starts on its own.

Further, the Shuttle widget appears in notification pane, but the controls show the **Play** button, although the track is already playing. (When a track is playing, the "play" button should change to "pause". But this does not happen.)

Regardless of that, if I tap on the **Play** button, it stops playing!

This has happened at least 5 times, but is not repeatable.

**Other factors:**
1. I have installed Nova launcher.

2. Neither the phone nor Nova are configured to have gestures on locked screen to launch shuttle or any other music app. (The phone is configured to launch camera and torch with gestures on locked screen.) Even then I tried many kinds of gestures, but there is no unexpected launching of any app.

3. In all cases, the headphone was not plugged in.

**Comment by timusus** [comment]
This sounds like a device/firmware bug to me. Shuttle does not have any kind of gesture detection, least of all on the lock screen. Most likely, whatever this bug is, it's sending a global 'play' command, which is then received by Shuttle (being your most recently used media player). I would suggest contacting the OxygenOS devs for more information.

As for the incorrect state of the play button, that is tracked here: #151
