### ISSUE TITLE
Google assistant integration

### ISSUE THREAD

**Issue by dhruvkb** [timusus/Shuttle#258]
**Shuttle version:**
 
 v1.6.7 free
 
**Device, OS:**

Moto G5 Plus, Android 7.0 Nougat

**Description of enhancement:**
 
Integration with Assistant as provider of music, like Spotify or Play Music.
 
**Expected outcome:**

Shuttle should appear with other suggestions as a music provider with the ability to choose it as the default.

**Comment by Ufeldraku** [comment]
Your Shuttle version is really updated.

But, yeah, it should be nice to have the integration with GAssistant.

**Comment by BigNickBurgess** [comment]
I don't think this will work.  Those music providers are 'Streaming' providers not phone based music.  

For phone based music you'd use the assistant to load a third party app or via Google Home you'd cast or connect via Bluetooth.  That's why the only providers are GPM and Spotify currently, your self uploaded GPM music works via the assistant without a subscription (and subsequently it then uses the phone based music files if they match up exactly).

**Comment by dhruvkb** [comment]
@timusus I did not know about that at all! Thanks a lot. _TIL_ that you can specify the player to Assistant.

**Comment by duanemoody** [comment]
> You can say 'ok Google, play <artis/album/song> with Shuttle', and it will work.

If I ask it to "Play <artist> with Shuttle" it replies in the affirmative, opens Shuttle to the Artists tab and then stops there without playing anything.

**Comment by TTLucian** [comment]
This is not working. "Open shuttle" works but doesn't play anything.
