### ISSUE TITLE
Can't manage multiple songs at once. 

### ISSUE THREAD

**Issue by GeneAnderson** [timusus/Shuttle#279]
**Shuttle version:**
 
 v2.02 (Upgraded) 
 
**Device, OS:**
 
Samsung Galaxy S8+, Android 7.0

**Description of bug:**
 
Can't mass add songs to a playlist or mass delete songs. Can only do it one by one. 
 
**Steps to reproduce:**
 
 1. From the Now Playing screen, press the Up Next bar at the bottom. 
 2. Select multiple songs
 3. Press the trash/delete button
Or
3a. Press Add Button and select a playlist 
 
**Expected outcome:**
 
A pop-up asking if it's okay to delete 
Or
A notification saying the songs were added to whatever playlist 
 
**Observations/Actual Result:**
 
 If I press the Trash button, nothing happens.

If I press the Add button, I can pick a new or existing playlist, but the songs never get added.

**Comment by adneal** [comment]
These things are fixed in the latest `2.0.3` release; although, we've replaced the action to delete multiple songs from the queue with an action to simply remove them from the queue. If you want to trash them then you'll have to batch select them from the song tab or search screen. But seeing that you're wanting to batch delete from the queue, I'll probably add that option back and it'll be in the next beta update/release. If you keep seeing this error happen in `2.0.3+` we can reopen this issue.
