### ISSUE TITLE
Recently added playlist is broken

### ISSUE THREAD

**Issue by TedManowar** [timusus/Shuttle#320]
**Shuttle version:**
 
 v2.0.2 and onward
 
**Device, OS:**
 
Samsung A3 2016 
and 
Huawei Mate 10 Lite 

both with Android 7

**Description of bug:**
 
The Recently Added playlist doesn't work properly. The order of folder creation isn't retained. The playlist displays my entire 181 album collection in mixed order. I have tried the filter button but it doesn't remedy the issue. 

**Steps to reproduce:**

I download a new album into my device 
 
**Expected outcome:**
 
I expect it to be displayed 1st in the Recently added playlist
 
**Observations/Actual Result:**
 
The order is mixed

I manually installed v2.0.1 and it works fine

**Comment by timusus** [comment]
Recently added uses the timestamp of the MediaStore - the time when the file is 'scanned' by Android's MediaScanner, rather than the file creation date - as this is less 'expensive' to retrieve (it's already available in the database).

This should still work - usually files are scanned shortly after they're added.

When you say
> I expect it to be displayed 1st in the Recently added playlist

So, you're saying the newly added songs are showing up in 'recently added', but the order of them isn't retained - newer songs don't necessarily show up higher than older songs?

**Comment by TedManowar** [comment]
At the moment, the most recent folder on my phone is displayed 3d. Have a look at the screenshots:

![screenshot_20180404-142257](https://user-images.githubusercontent.com/8566910/38305272-f8d82b90-3814-11e8-9c7e-cb123143f661.png)
![screenshot_20180404-142749](https://user-images.githubusercontent.com/8566910/38305274-fa6c2024-3814-11e8-8f40-9986b7815152.png)
