### ISSUE TITLE
MediaPlayer prepare vs prepareAsync

### ISSUE THREAD

**Issue by peyman-abdi** [timusus/Shuttle#328]
first let me thank you for your great work, Shuttle is a very well designed and written app, and also thank you for making it opensource

I am working on Shuttle to add some online features like streaming from remote servers.
while developing I found that u are using mediaplayers prepare instead of prepareAsync and this method is getting called from the main thread. so I was wondering if this could impact the ux while streaming and if its possible to call musicservice from a background thread or do it Rx way.

**Comment by timusus** [comment]
Yes, you would need to use `prepareAsync` if you want to play from a streaming source. This would require refactoring of the `MultiPlayer`, as it currently calls the synchronous `prepare()`, as you've observed.

This would be a welcome change, as there most likely already is a UI performance issue caused by this synchronous prepare.
