### ISSUE TITLE
Shuttle not staying in memory

### ISSUE THREAD

**Issue by neekless** [timusus/Shuttle#343]
**Shuttle version:**
 
 Shuttle+ v2.0.5 beta2
 
**Device, OS:**
 
Nexus 6P, Android 8.1.0 ABC Rom

**Description of bug:**
 
App randomly gets killed while playing music
 
**Steps to reproduce:**
 
 1. Play music
 2. Use other lightweight apps or do nothing with the screen off
 3. Music stops, notification disappears
 
**Expected outcome:**
 
Music should continue playing, especially when not doing any other performance intensive tasks
 
**Observations/Actual Result:**
 
 App seems like it's getting killed despite having more than enough RAM. This issue also did not happen prior to the new beta, with all device settings staying the same.

I'm not familiar with development so I'm most likely wrong, but I took a look at the commits and it may have something to do with MusicService?

**Comment by timusus** [comment]
This is the second report I've seen of such behaviour. I think it has to do with some of the refactoring that has taken place in the MusicService..

**Comment by balzabalza** [comment]
I experience the same behaviour from time to time, but I don't know if it's a bug or the way my Nexus 5x balances multitasking and limited amount of ram.

**Comment by timusus** [comment]
I can't seem to reproduce this issue on my Nexus 6P. 

I'm running the ADB commands:
`cmd appops set com.simplecity.amp_pro.debug RUN_IN_BACKGROUND deny`
`adb shell am make-uid-idle com.simplecity.amp_pro.debug`
Which should simulate the system trying to remove the background service, since it's not allowed to run in the background. But, the notification persists and Shuttle is able to continue playing.

I've also tried:
`adb shell am send-trim-memory com.simplecity.amp_pro.debug RUNNING_CRITICAL`
To simulate low memory in Shuttle itself, but the app continues playback.

Shuttle is still requesting a WakeLock when playback begins, and that appears to be working correctly.

**Comment by neekless** [comment]
Maybe it's not due to memory/background but due to something else?

I usually listen to music on my commute to work, which is around 1.5 hours. On some days, this issue doesn't happen at all. On some days, it can happen 3 to 4 times during the journey. So I cannot reliably reproduce it too.

Is there a way to capture logs when it happens?

**Comment by 4ut0-M-4t** [comment]
**Device/OS:**
SGN 4 / Android 6.0.1
**Shuttle version:**
2.0.5 beta2

Definitely not a low memory problem. Shuttle stops after the first song even when a device remains idle (whether it's locked or not).

**Comment by timusus** [comment]
@4ut0-M-4t does this happen every time? Is this with shuffle on or off? And repeat mode on/off? Does it make any difference if you change the modes?

**Comment by Bluerobot1234** [comment]
I'm also getting this issue from time to time on my OnePlus 3T, Android 8.0
Mostly happens when my device is locked

**Comment by GeoZac** [comment]
@timusus I had posted a error log on Slack after facing a similar issue. The logs had some IntentReceiver leak error.

**Comment by timusus** [comment]
@GeoZac I haven't looked at those (or if I have I don't remember). The IntentReceiver leak just happens if the MusicService shuts down.. The leak is a 'problem', but it's more a side effect of Shuttle shutting down, rather than a cause of the issue.

Are you still experiencing the issue?

**Comment by GeoZac** [comment]
@timusus I get it from time to time,will dig deeper next time

**Comment by 4ut0-M-4t** [comment]
Sorry for delayed reply.
**@timusus** It does not happen every time. Repeat mode's set to `All`. Shuffle mode is always `OFF`, although, funnily enough, it used to be a separate bug - shuffle automatically turning itself `ON` every time I started Shuttle. But I do not experience this issue with the latest Beta.

Another (though related) issue is widget. It ignores you pressing `Play` button unless you start the app and let it retrieve data from media database, after that, if you press `Play` within app's interface, it will start playing and REstart after a couple of seconds. The problem might be derived from the fact that I have tampered with Shuttle's `SharedPreferences` (to temporarily enable folder browsing) as it had never happened before that moment.

**Comment by farmerbb** [comment]
Also experiencing this issue on the Essential Phone running Android P DP5.  I see the following message in logcat when the app gets killed:

`08-01 16:59:55.259 W/ActivityManager(977): Stopping service due to app idle: u0a267 -11m46s502ms com.simplecity.amp_pro/com.simplecity.amp_library.playback.MusicService`

For whatever reason, Android is thinking that the app has gone into the background stopped state, and kills the service accordingly.  I'm going to try disabling battery optimizations for Shuttle in the system settings to see if this helps - this issue occurs for me pretty consistently after 10 - 15 minutes of playing music.

**Comment by korgano** [comment]
Updated to v2.0.6 on my Android 5.1.1 phone, and I'm getting this issue every time I switch focus from Shuttle to any other app. Usually I'll get 2-3 minutes of continued audio, then it crashes/whatever and forces me to back out of the selected media to reselect it from the playlist view, because all the media info is just blanked out and pressing play just starts a random song.

IIRC, I was on Shuttle v1.something before this, and had no problems.

**Comment by SuperSandro2000** [comment]
Didn't occur to me anymore in recent usage
