### ISSUE TITLE
The support for the beta testing program is lost now!

### ISSUE THREAD

**Issue by raindropsfromsky** [timusus/Shuttle#494]
1. The [Google play page](https://play.google.com/store/apps/details?id=another.music.player) has a link to [Google+ page for beta testing](https://plus.google.com/communities/112365043563095486408). But the Google+ website does not exist now. Thus the primary link for the beta testing is lost.
2. The app itself does not contain a "join as beta tester!" link.
3. The GitHub also does not have any provision to list beta apk files.

Thus all three major ways to attract people to do beta testing are closed. 
Please correct them.

**Comment by timusus** [comment]
Thanks for pointing that out, the store description needs to be updated.

There is no beta version in rotation at the moment.

Beta apk files are distributed via the Play Store, not Github.

**Comment by raindropsfromsky** [comment]
> There is no beta version in rotation at the moment.
Yes, of course. But in other apps, if we opt to become a beta tester, it automatically upgrades to beta version _whenever it is available_. That option should be available to the Shuttle users.

**Comment by timusus** [comment]
That option is available. If you are opted-in to the beta, you will receive updates when they become available. Maybe the link isn't visible on the Play Store because there's no current beta version?

**Comment by raindropsfromsky** [comment]
IMHO the induction to beta testing should be through a link that he has to click to show that he agrees to be a beta tester. 

It should not be by providing a download link whenever a beta is available. Otherwise, if I want to be a beta tester, I will have to constantly visit the Google Play page to check if there is a beta available.

The consent link would always be available at the website (and also in the app), regardless of whether the beta is there or not. Once the user gives his consent to become a beta tester, the betas would be upgraded in his mobile. If he has not given his consent, a beta will be ignored.

**Comment by timusus** [comment]
Shuttle's beta testing program is facilitated by the Google Play Store. Once you've opted-in, you automatically receive updates. I don't have any control over whether the opt-in link is listed in the Play Store.

It sounds like you're just having trouble finding that opt-in link, which might simply be because there's no current beta?

In any case, here's the link to opt in to Shuttle (free) beta testing:
https://play.google.com/apps/testing/another.music.player

And Shuttle+:
https://play.google.com/apps/testing/com.simplecity.amp_pro

Google+ has been replaced with Discord:
https://discord.gg/4Z5EU7K
