### ISSUE TITLE
Artist/Album Issue

### ISSUE THREAD

**Issue by BigBlakBoi** [timusus/Shuttle#52]
I've had an issue for a long while where a large number of artists are missing from the artist tab, and instead are all stored under one artist's name. What I realized all those songs have in common is they have no album name, and therefore are given the default album name "music". I would ask that you either fix this sorting issue, or you just remove the "music" album tag all together, because the app is regestering
 all songs with the album name "music" under the same artist in the artist tab. Below are two images to show what I mean.

![image1](https://cloud.githubusercontent.com/assets/26145281/23525773/8f0c20fe-ff5d-11e6-8263-52835c04678a.jpg)

![image2](https://cloud.githubusercontent.com/assets/26145281/23525776/9340ff96-ff5d-11e6-84c4-ae00efe71374.jpg)

**Comment by phase** [comment]
If a song doesn't have an album in the metadata, the album is set to the name of the folder that the song is in.

**Comment by BigBlakBoi** [comment]
Is there a way to fix this? Because it's impossible for the songs to not be stored in a folder.

**Comment by phase** [comment]
Renaming the folder or set the name of the album to the name of the song, but I believe that all ongs currently have to be stored in an album.

**Comment by BigBlakBoi** [comment]
Right but renaming the folder wouldn't fix the problem and renaming every song's album is tedious work. I'm positive this is a problem on the app's end and not mine because I have 3 other music players that don't have this issue, it's limited to shuttle only.

**Comment by phase** [comment]
Oh, I assumed the folder that your music was in was named _Music_ (like mine are).

**Comment by timusus** [comment]
This is something that can and should be fixed in Shuttle.

There is some logic in the `DataManager` class (or called from within that class) which builds the list of songs, albums and artists used throughout the app.

This logic assumes that the 'album' tag is present, and uses it to group songs together. So, my guess is if the album tag is null, all songs under that album get grouped together as they all share 'null' as the parent album. 

This should be a relatively simple fix, it just requires some thought & testing.

**Comment by BigBlakBoi** [comment]
Thanks, I really appreciate your reply. Shuttle is my #1 preferred music player app but this problem is really frustrating which is why I use others sometimes. Really hope you can get this fixed in the next update.
