### ISSUE TITLE
Album Shuffle

### ISSUE THREAD

**Issue by qwarkys** [timusus/Shuttle#59]
Please add a feature to play a random album (similar to shuffle, but by album rather than song).  Alternatively, the ability to create a playlist with all albums in random order.  In each case, songs within the album would play in standard order.

**Comment by samyuyitung** [comment]
Hi,
I'm interesting in picking this up, how do you think this should be implemented?
I was thinking that the ability to create a playlists of all albums makes more sense that just playing a random album.
UI wise, could this be similar to how the shuffle all is currently done for songs with the shuffleview at the top of the list.

Thoughts?

**Comment by timusus** [comment]
Probably easiest to discuss on [Slack](http://shuttle-slack-inviter.herokuapp.com/), if you like.

I'm not quite sure how this one should be implemented. Somehow, 'album shuffle' mode needs to be started. It would then just generate a list of albums, shuffle them, then retrieve a list of their songs. Those songs would then be passed to the MusicService queue.

**Comment by clockler** [comment]
Since there's been no discussion of this but it's one of my favourite features (of foobar2000 - I don't think I've *ever* seen it anywhere else) I could suggest some details as to how I would personally envision it working:

* Rather than a dedicated mode generating a playlist for you, album shuffle would be a mode of the shuffle functionality exactly as the Repeat Playlist/Repeat Track are modes of the repeat functionality - it would be changed to No Shuffle/Shuffle Tracks/Shuffle Albums, cycling on press. I'd suggest a disc icon overlaid on the shuffle icon to visually denote album shuffle being enabled.
* For consistency with the existing shuffle functionality, it should definitely sort the current queue exactly as the current behaviour does, rather than shuffling live.
* There is a usecase for using album shuffle but not necessarily having every track of an album in the queue - so you can't just reduce the queue to albums only then add all tracks from those albums naively to a new queue. You would have to map all tracks in the queue to albums while building a list of albums, shuffle the list of albums, then re-add all tracks of each album from those lists. I assume you could use the keys of the map for the album list, so you'd essentially reduce to a `Map<Album, List<Song>>` or similar.

It's kind of against the spirit of the feature but I think it's fine to leave the tracks in the order they appeared in the queue, since that's just down to the user's preference. A final touch would be a "Shuffle all" button on the Albums tab, appearing identically to the one on the Songs tab (regardless of view type).

(Yes, I came here to suggest this feature. Didn't even know Shuttle had gone open source, because I'm a smart.)
