### ISSUE TITLE
Broadcasted song progress is wrong

### ISSUE THREAD

**Issue by RageKnify** [timusus/Shuttle#82]
**Shuttle version:**
 v1.6.5-beta5
 
**Device, OS:**
 OnePlus X Lineage 14.1(7.1.1)

**Description of bug:**
 Other apps don't get the correct information in regards to song progress. With my pebble smartwatch, if I play a song up to a certain point(let's say 1:30) and then I skip to the next song instead of saying that it's at 0 seconds it will say that I'm at the point that the previous song was at.(in my example it would say the second song is immediately at 1:30 or 1:31)
 
**Steps to reproduce:**
 1. Step 1 Open Shuttle and get a song playing
 2. Step 2 use another app that takes action over media playback(eg. KLWP/Pebble smartwatch) to skip to the next song.
 
**Expected outcome:**
 The Pebble should say that the second song is at it's beginning. 
 
**Observations/Actual Result:**
 Instead it thinks that it's at the point the previous song was at.

I've tried the same thing withe default music app and it doesn't have the same problem as Shuttle.

**Comment by geecko86** [comment]
@timusus This is because `PLAY_STATE_CHANGED` is not sent to `updateMediaSession` when you skip to the next song - only `META_CHANGED`.

The solution is to ensure `PLAY_STATE_CHANGED` is sent as well when skipping the track.

I thought of making `updateMediaSession` call itself with `PLAY_STATE_CHANGED` when its parameter is `META_CHANGED` but maybe you'd like a cleaner solution.

(This is crucial for proper Sync support in QuickLyric)

**Comment by timusus** [comment]
>The solution is to ensure PLAY_STATE_CHANGED is sent as well when skipping a track.

@geecko86 I don't agree with this. A track change event is `META_CHANGED`. External receivers should acknowledge this event and reset their current media position as required. This has been the case for many years, since the original [Android Music Player[(https://github.com/android/platform_packages_apps_music/blob/master/src/com/android/music/MediaPlaybackService.java#L941)

However, since @RageKnify says this is working with the default media player, I suspect there is another issue at play. I'll continue to investigate this one.

**Comment by timusus** [comment]
@RageKnify according to Pebble's own documentation (and the information Shuttle sends to Pebble), Pebble only receives the artist, album and song name, when the track changes. This tells me that Pebble is tracking the song progress itself. Presumably pebble just starts counting when the track changes.. I'm really not sure. It's possible that they're gleaning the current progress from some other messages Shuttle is broadcasting, but to me it looks like that information is accurate.

Are you able to reproduce this issue anywhere other than the Pebble device? I don't have a Pebble, but it would be useful if I could see this bug in the flesh.

**Comment by geecko86** [comment]
> External receivers should acknowledge this event and reset their current media position as required. 

This implies the track you skip to will always start at position zero, which is not true.

>  it would be useful if I could see this bug in the flesh

You won't be able to see the position value directly (unless you debug the project) but QuickLyric will misbehave if you reproduce the steps which @RageKnify described.

You're right that I don't know the specifics of how a player should handle these things and in what order these events need to be broadcasted, but [here](https://github.com/geecko86/QuickLyric/blob/master/QuickLyric/src/main/java/com/geecko/QuickLyric/services/NotificationListenerService.java#L177) I use controller.getPlaybackState().getPosition() to get the position. 

With Shuttle it will give me the position for the previous track, while [controller.getPlaybackState().getMetadata()](https://github.com/geecko86/QuickLyric/blob/master/QuickLyric/src/main/java/com/geecko/QuickLyric/services/NotificationListenerService.java#L168) will have the information for the current track. Clearly something's wrong.

**Comment by timusus** [comment]
Thanks for the additional information.

>This implies the track you skip to will always start at position zero, which is not true.

Right, but that's an implementation detail for the external receiver to worry about. In the case of QuickLyric, as you've pointed out you solve this by calling `controller.getPlaybackState().getPosition()`. So sending a `PLAY_STATE_CHANGED` event when the track is changed isn't really going to fix the problem. I guess that's all I was talking about.

>Clearly something's wrong.

I absolutely agree, I'm just trying to work out what and how to fix it.
