### ISSUE TITLE
Search behavior is very inconsistent

### ISSUE THREAD

**Issue by wlevine** [timusus/Shuttle#84]
**Shuttle version:**
 
 v1.6.4
 
**Device, OS:**
 
Sony Xperia X Compact, Android 7.0

**Description of bug:**

Searching for "dylan" doesn't match "Bob Dylan", but "machover" matches "Tod Machover"

"over" doesn't match "Tod Machover", but does match "Love" (because they share the substring "ove"???).

"{" matches "{QI}, but not "{HTSK}" (both are songs on the same album).

Lots of other weird behavior with fuzzy matches showing up, and exact matches completely missing.

I haven't looked at the code yet, but if you point me in the right direction, or explain what's going on, maybe I could help with a fix.

P.S. Thanks so much for making Shuttle and open sourcing it! It's the one music app I found that just does what I want and stays out of my way.

**Comment by timusus** [comment]
I believe this is resolved with #42, which is available for beta testing (Play Store), or in the release channel on github, if you'd like to try it out.

Otherwise, it will be released in v1.6.5.

**Comment by wlevine** [comment]
Thanks, I didn't realize there was a beta.

I can confirm that the bug is at least half fixed. All the matches I expect to see show up.

Searching is much slower now. It now takes 1-3 seconds for results to appear.

Also there are still a large number of irrelevant results shown. If I type "adventures" to find the song "Adventures in Solitude", the first thing I see are several artists that don't resemble "adventures" at all ("At The Drive-In", "Car Seat Headrest", etc.). Beyond that I have to scroll thru dozens of irrelevant albums to find the song I am looking for. "Adventures in Solitude" is the only song/artist/album I have that actually contains "adventures", so I would expect it to be the first result. If it were up to me, I would get rid of the fuzzy matching entirely, but if you want to keep it, it seems the criteria needs to be tightened up a lot. It probably would also speed up the search significantly.

**Comment by timusus** [comment]
I don't see a compelling reason to remove fuzzy searching, It was added to solve the issue many people have, where there tags are incorrect, or their songs contain special characters, and would otherwise not show up in a search.

The 'irrelevant results' are likely just fuzzy-matches. The word 'adventures' must be a >70% match with 'at the drive in' using the jaro-winkler string similarity algorithm. I am considering increasing this threshold again, I think it was lowered for the wrong reasons. The more relevant results are bubbled to the top though, so it shouldn't matter.

I'm currently implementing a search filter which will allow you to choose whether fuzzy searching is enabled, whether to search the title & fields of just the title, and whether to search for songs, albums or artists. I think this will help speed up the search time. Track the progress of this one here:  #83
